DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON
(
    ID        NUMBER PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255),
    LASTNAME  VARCHAR(255),
    BIRTHDAY  DATE,
    GENDER    VARCHAR(1)
);

INSERT INTO PERSON (FIRSTNAME, LASTNAME, BIRTHDAY, GENDER)
VALUES ('Marin', 'Markovic', '2021-07-10', 'M'),
       ('Luka', 'Lukic', '2021-07-10', 'M'),
       ('Roman', 'Romankovic', '2021-07-10', 'M'),
       ('Andrea', 'Andreic', '2021-07-10', 'Z');

DROP TABLE IF EXISTS CAR_RENTAL;

CREATE TABLE CAR_RENTAL
(
    ID        NUMBER PRIMARY KEY AUTO_INCREMENT,
    PERSON_ID NUMBER,
    CAR_ID    NUMBER,
    DATE_FROM DATE,
    DATE_TO   DATE
);

INSERT INTO CAR_RENTAL (PERSON_ID, CAR_ID, DATE_FROM, DATE_TO)
VALUES (1, 3, '2021-07-10', '2021-07-15'),
       (1, 4, '2021-07-16', '2021-07-21'),
       (2, 1, '2021-07-10', '2021-07-12');

DROP TABLE IF EXISTS CAR;

CREATE TABLE CAR
(
    ID    NUMBER PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(255),
    MODEL VARCHAR(255),
    PRICE NUMBER(10)
);

INSERT INTO CAR (BRAND, MODEL, PRICE)
VALUES ('VW', 'GOLF 7', 100),
       ('VW', 'PASSAT', 800),
       ('AUDI', 'A6', 1000),
       ('AUDI', 'A3', 600),
       ('BMW', 'X5', 1000);

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    ID        NUMBER PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255),
    LASTNAME  VARCHAR(255),
    USERNAME  VARCHAR(255),
    PASSWORD  VARCHAR(255),
    ROLES     VARCHAR(255)
);

INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASSWORD, ROLES)
VALUES ('Ivo', 'Ivić', 'ivoivic', '$2a$10$lkMXCDzy/bny.jQv9PU32eLMNX5xI2Rd8KQbSPJe8.bsRA8wykz6W', 'EDITOR,VIEWER');

